### ISSUE TITLE
Frequent Blue Screen Flickers

### ISSUE THREAD

**Issue by Flyhalf205** [arco/android_hardware_qcom_display-legacy#9]
I get frequent blue flickers since using this git. Not sure why. Here is my kernel if I've done something wrong. https://github.com/Flyhalf205/vigor_aosp_kernel

Any ideas or hints? Thanks!

**Comment by arco** [comment]
Hmm, that's strange. I can't see anything special in the kernel that sticks out. Do you have the same issue if using the _old branch for display-legacy?

**Comment by Flyhalf205** [comment]
No issue that I can remember of. We were using an extremely older display-legacy.

https://github.com/Flyhalf205/device_htc_vigor/tree/8b6da238c060f92d3ac1719452c509a5cc8dce5d/display-legacy

It's not that big of a deal. It mostly happens during any type of animation.
